// packages/react-native/src/fields/AutocompleteField.tsx
import React, { useState } from 'react';
import { View, Text, Pressable, FlatList } from 'react-native';
import type { FieldComponentProps } from '../types.js';
import { Input } from '../ui/Input.js';
import { cn } from '../ui/utils.js';

/**
 * Autocomplete field using TextInput + filtered FlatList dropdown.
 */
export function AutocompleteField({
  name,
  value,
  onChange,
  onBlur,
  options,
  placeholder,
  disabled,
}: FieldComponentProps) {
  const [search, setSearch] = useState(String(value ?? ''));
  const [open, setOpen] = useState(false);

  const filtered = (options ?? []).filter((opt) =>
    opt.label.toLowerCase().includes(search.toLowerCase()),
  );

  return (
    <View>
      <Input
        testID={name}
        value={search}
        onChangeText={(text) => {
          setSearch(text);
          setOpen(true);
        }}
        onBlur={() => {
          // Delay close to allow press on options
          setTimeout(() => {
            setOpen(false);
            onBlur();
          }, 200);
        }}
        placeholder={placeholder}
        editable={!disabled}
      />
      {open && filtered.length > 0 && (
        <View className="mt-1 max-h-48 rounded-md border border-gray-200 bg-white shadow-sm">
          <FlatList
            data={filtered}
            keyExtractor={(item) => item.value}
            keyboardShouldPersistTaps="handled"
            renderItem={({ item }) => (
              <Pressable
                onPress={() => {
                  onChange(item.value);
                  setSearch(item.label);
                  setOpen(false);
                }}
                className={cn(
                  'px-3 py-2',
                  value === item.value && 'bg-blue-50',
                )}
              >
                <Text className="text-sm text-gray-900">{item.label}</Text>
              </Pressable>
            )}
          />
        </View>
      )}
    </View>
  );
}

// packages/svelte/src/fields/AutocompleteField.svelte
<script lang="ts">
  import type { FieldComponentProps } from '../types.js';
  import Input from '../ui/Input.svelte';
  import { cn } from '../ui/utils.js';

  let { name, value, onChange, onBlur, options, placeholder, disabled }: FieldComponentProps = $props();

  let open = $state(false);
  let search = $state(String(value ?? ''));

  const filtered = $derived(
    (options ?? []).filter((opt) =>
      opt.label.toLowerCase().includes(search.toLowerCase()),
    ),
  );

  function handleSelect(optValue: string, optLabel: string) {
    onChange(optValue);
    search = optLabel;
    open = false;
  }
</script>

<div class="relative">
  <Input
    id={name}
    {name}
    value={search}
    oninput={(e) => {
      search = e.currentTarget.value;
      open = true;
    }}
    onfocus={() => (open = true)}
    onblur={() => {
      setTimeout(() => {
        open = false;
        onBlur();
      }, 200);
    }}
    {placeholder}
    {disabled}
    autocomplete="off"
  />
  {#if open && filtered.length > 0}
    <div
      class={cn(
        'bg-popover text-popover-foreground absolute z-50 mt-1 max-h-48 w-full overflow-auto rounded-md border p-1 shadow-md',
      )}
    >
      {#each filtered as opt}
        <button
          type="button"
          class={cn(
            'hover:bg-accent hover:text-accent-foreground w-full cursor-default rounded-sm px-2 py-1.5 text-left text-sm',
            value === opt.value && 'bg-accent',
          )}
          onmousedown={(e) => { e.preventDefault(); handleSelect(opt.value, opt.label); }}
        >
          {opt.label}
        </button>
      {/each}
    </div>
  {/if}
</div>
