// packages/react-native/src/fields/CheckboxField.tsx
import React from 'react';
import { View, Text, Pressable } from 'react-native';
import type { FieldComponentProps } from '../types';
import { cn } from '../ui/utils';

export function CheckboxField({
  name,
  value,
  onChange,
  onBlur,
  disabled,
}: FieldComponentProps) {
  const checked = Boolean(value);

  return (
    <Pressable
      testID={name}
      disabled={disabled}
      onPress={() => {
        onChange(!checked);
        onBlur();
      }}
      className="flex-row items-center"
    >
      <View
        className={cn(
          'h-5 w-5 items-center justify-center rounded border',
          checked ? 'border-blue-600 bg-blue-600' : 'border-gray-300 bg-white',
          disabled && 'opacity-50',
        )}
      >
        {checked && <Text className="text-xs font-bold text-white">✓</Text>}
      </View>
    </Pressable>
  );
}

// packages/svelte/src/fields/CheckboxField.svelte
<script lang="ts">
  import type { FieldComponentProps } from '../types.js';
  import { cn } from '../ui/utils.js';

  let { name, value, onChange, onBlur, disabled }: FieldComponentProps = $props();
</script>

<input
  type="checkbox"
  id={name}
  {name}
  checked={Boolean(value)}
  onchange={(e) => onChange(e.currentTarget.checked)}
  onblur={onBlur}
  {disabled}
  class={cn(
    'peer border-primary ring-offset-background focus-visible:ring-ring data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground h-4 w-4 shrink-0 rounded-sm border focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50',
  )}
/>
