// packages/react/src/fields/NumberField.tsx
import React from 'react';
import type { FieldComponentProps } from '../types.js';
import { Input } from '../ui/Input.js';

export function NumberField({ name, value, onChange, onBlur, placeholder, disabled }: FieldComponentProps) {
  return (
    <Input
      id={name}
      name={name}
      type="number"
      value={value === '' || value === undefined || value === null ? '' : String(value)}
      onChange={(e) => {
        const v = e.target.value;
        onChange(v === '' ? '' : Number(v));
      }}
      onBlur={onBlur}
      placeholder={placeholder}
      disabled={disabled}
    />
  );
}

// packages/svelte/src/fields/NumberField.svelte
<script lang="ts">
  import type { FieldComponentProps } from '../types.js';
  import Input from '../ui/Input.svelte';

  let { name, value, onChange, onBlur, placeholder, disabled }: FieldComponentProps = $props();
</script>

<Input
  id={name}
  {name}
  type="number"
  value={value === '' || value === undefined || value === null ? '' : String(value)}
  oninput={(e) => {
    const v = e.currentTarget.value;
    onChange(v === '' ? '' : Number(v));
  }}
  onblur={onBlur}
  {placeholder}
  {disabled}
/>
