// packages/react/src/fields/TextAreaField.tsx
import React from 'react';
import type { FieldComponentProps } from '../types.js';
import { Textarea } from '../ui/Textarea.js';

export function TextAreaField({ name, value, onChange, onBlur, placeholder, disabled }: FieldComponentProps) {
  return (
    <Textarea
      id={name}
      name={name}
      value={String(value ?? '')}
      onChange={(e) => onChange(e.target.value)}
      onBlur={onBlur}
      placeholder={placeholder}
      disabled={disabled}
    />
  );
}

// packages/svelte/src/fields/TextAreaField.svelte
<script lang="ts">
  import type { FieldComponentProps } from '../types.js';
  import Textarea from '../ui/Textarea.svelte';

  let { name, value, onChange, onBlur, placeholder, disabled }: FieldComponentProps = $props();
</script>

<Textarea
  id={name}
  {name}
  value={String(value ?? '')}
  oninput={(e) => onChange(e.currentTarget.value)}
  onblur={onBlur}
  {placeholder}
  {disabled}
/>
