// packages/react-native/src/components/DefaultTemplate.tsx
import React from 'react';
import { View, Text } from 'react-native';
import type { TemplateComponentProps } from '../types.js';
import { Label } from '../ui/Label.js';
import { cn } from '../ui/utils.js';

/**
 * Default template wrapper for form fields.
 * Provides label, description text, and error message display.
 * Uses React Native View/Text with NativeWind styling.
 */
export function DefaultTemplate({
  name,
  label,
  description,
  error,
  children,
}: TemplateComponentProps) {
  return (
    <View className={cn('gap-2')} testID={`field-${name}`}>
      {label && (
        <Label className={cn(error && 'text-red-500')}>
          {label}
        </Label>
      )}
      {children}
      {description && (
        <Text className="text-sm text-gray-500">{description}</Text>
      )}
      {error && (
        <Text className="text-sm font-medium text-red-500" accessibilityRole="alert">
          {error}
        </Text>
      )}
    </View>
  );
}

// packages/svelte/src/components/DefaultTemplate.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { cn } from '../ui/utils.js';
  import Label from '../ui/Label.svelte';

  interface Props {
    name: string;
    label?: string;
    description?: string;
    error?: string;
    children: Snippet;
  }

  let { name, label, description, error, children }: Props = $props();
</script>

<div class={cn('space-y-2')} data-field={name}>
  {#if label}
    <Label for={name} class={cn(error && 'text-destructive')}>
      {#snippet children()}
        {label}
      {/snippet}
    </Label>
  {/if}
  {@render children()}
  {#if description}
    <p class="text-muted-foreground text-sm">{description}</p>
  {/if}
  {#if error}
    <p class="text-destructive text-sm font-medium" role="alert">{error}</p>
  {/if}
</div>
