// packages/react/src/components/FieldSet.tsx
import React from 'react';
import type { FieldSchema, FieldsetConfig } from '../types.js';
import { Field } from './Field.js';
import { cn } from '../ui/utils.js';

export interface FieldSetProps {
  config: FieldsetConfig;
  schema: Record<string, FieldSchema>;
}

/**
 * Groups fields together with an optional legend.
 */
export function FieldSet({ config, schema }: FieldSetProps) {
  return (
    <fieldset className={cn('space-y-4 rounded-lg border p-4')}>
      {config.legend && <legend className="px-2 text-lg font-semibold">{config.legend}</legend>}
      {config.fields.map((fieldName) => {
        const fieldSchema = schema[fieldName];
        if (!fieldSchema) return null;
        return <Field key={fieldName} name={fieldName} fieldSchema={fieldSchema} />;
      })}
    </fieldset>
  );
}

// packages/svelte/src/components/FieldSet.svelte
<script lang="ts">
  import type { FieldSchema, FieldsetConfig } from '../types.js';
  import { cn } from '../ui/utils.js';
  import Field from './Field.svelte';

  interface Props {
    config: FieldsetConfig;
    schema: Record<string, FieldSchema>;
  }

  let { config, schema }: Props = $props();
</script>

<fieldset class={cn('space-y-4 rounded-lg border p-4')}>
  {#if config.legend}
    <legend class="px-2 text-lg font-semibold">{config.legend}</legend>
  {/if}
  {#each config.fields as fieldName}
    {#if schema[fieldName]}
      <Field name={fieldName} fieldSchema={schema[fieldName]} />
    {/if}
  {/each}
</fieldset>
