// packages/react-native/src/ui/Button.tsx
import React from 'react';
import { Pressable, Text } from 'react-native';
import { cn } from './utils.js';

export interface ButtonProps {
  className?: string;
  textClassName?: string;
  onPress?: () => void;
  disabled?: boolean;
  variant?: 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost';
  size?: 'default' | 'sm' | 'lg';
  children: React.ReactNode;
  testID?: string;
}

const variantClasses: Record<string, string> = {
  default: 'bg-blue-600',
  destructive: 'bg-red-600',
  outline: 'border border-gray-300 bg-white',
  secondary: 'bg-gray-200',
  ghost: '',
};

const variantTextClasses: Record<string, string> = {
  default: 'text-white',
  destructive: 'text-white',
  outline: 'text-gray-900',
  secondary: 'text-gray-900',
  ghost: 'text-gray-900',
};

const sizeClasses: Record<string, string> = {
  default: 'h-10 px-4 py-2',
  sm: 'h-9 px-3',
  lg: 'h-11 px-8',
};

export function Button({
  className,
  textClassName,
  onPress,
  disabled = false,
  variant = 'default',
  size = 'default',
  children,
  testID,
}: ButtonProps) {
  return (
    <Pressable
      onPress={onPress}
      disabled={disabled}
      className={cn(
        'flex-row items-center justify-center rounded-md',
        variantClasses[variant],
        sizeClasses[size],
        disabled && 'opacity-50',
        className,
      )}
      testID={testID}
    >
      {typeof children === 'string' ? (
        <Text
          className={cn(
            'text-sm font-medium',
            variantTextClasses[variant],
            textClassName,
          )}
        >
          {children}
        </Text>
      ) : (
        children
      )}
    </Pressable>
  );
}

// packages/svelte/src/ui/Button.svelte
<script lang="ts">
  import { cn } from './utils.js';
  import type { Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';

  const variantClasses: Record<string, string> = {
    default: 'bg-primary text-primary-foreground hover:bg-primary/90',
    destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
    outline: 'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
    secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
    ghost: 'hover:bg-accent hover:text-accent-foreground',
    link: 'text-primary underline-offset-4 hover:underline',
  };

  const sizeClasses: Record<string, string> = {
    default: 'h-10 px-4 py-2',
    sm: 'h-9 rounded-md px-3',
    lg: 'h-11 rounded-md px-8',
    icon: 'h-10 w-10',
  };

  interface Props extends HTMLButtonAttributes {
    variant?: 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link';
    size?: 'default' | 'sm' | 'lg' | 'icon';
    children?: Snippet;
  }

  let { variant = 'default', size = 'default', class: className, children, ...rest }: Props = $props();

  const baseClasses = 'inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50';
</script>

<button
  class={cn(baseClasses, variantClasses[variant], sizeClasses[size], className)}
  {...rest}
>
  {#if children}
    {@render children()}
  {/if}
</button>
