// packages/react-native/src/ui/Label.tsx
import React from 'react';
import { Text } from 'react-native';
import { cn } from './utils.js';

export interface LabelProps {
  className?: string;
  children: React.ReactNode;
  testID?: string;
}

export function Label({ className, children, testID }: LabelProps) {
  return (
    <Text
      className={cn('text-sm font-medium leading-none text-gray-900', className)}
      testID={testID}
    >
      {children}
    </Text>
  );
}

// packages/svelte/src/ui/Label.svelte
<script lang="ts">
  import { cn } from './utils.js';
  import type { Snippet } from 'svelte';
  import type { HTMLLabelAttributes } from 'svelte/elements';

  interface Props extends HTMLLabelAttributes {
    children?: Snippet;
  }

  let { class: className, children, ...rest }: Props = $props();
</script>

<label
  class={cn(
    'text-sm leading-none font-medium peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
    className,
  )}
  {...rest}
>
  {#if children}
    {@render children()}
  {/if}
</label>
