// packages/svelte/src/components/DefaultTemplate.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { cn } from '../ui/utils.js';
  import Label from '../ui/Label.svelte';

  interface Props {
    name: string;
    label?: string;
    description?: string;
    error?: string;
    children: Snippet;
  }

  let { name, label, description, error, children }: Props = $props();
</script>

<div class={cn('space-y-2')} data-field={name}>
  {#if label}
    <Label for={name} class={cn(error && 'text-destructive')}>
      {#snippet children()}
        {label}
      {/snippet}
    </Label>
  {/if}
  {@render children()}
  {#if description}
    <p class="text-muted-foreground text-sm">{description}</p>
  {/if}
  {#if error}
    <p class="text-destructive text-sm font-medium" role="alert">{error}</p>
  {/if}
</div>

// packages/react/src/components/DefaultTemplate.tsx
import React from 'react';
import type { TemplateComponentProps } from '../types.js';
import { Label } from '../ui/Label.js';
import { cn } from '../ui/utils.js';

/**
 * Default template wrapper for form fields.
 * Provides label, description text, and error message display.
 * Uses shadcn/ui Label component.
 */
export function DefaultTemplate({ name, label, description, error, children }: TemplateComponentProps) {
  return (
    <div className={cn('space-y-2')} data-field={name}>
      {label && (
        <Label htmlFor={name} className={cn(error && 'text-destructive')}>
          {label}
        </Label>
      )}
      {children}
      {description && (
        <p className="text-sm text-muted-foreground">{description}</p>
      )}
      {error && (
        <p className="text-sm font-medium text-destructive" role="alert">
          {error}
        </p>
      )}
    </div>
  );
}
