// packages/svelte/src/components/FormProvider.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { Container } from '@speajus/diblob';
  import { resolveRegistries } from '@subschema/core';
  import { setFormContainerContext } from '../context.js';
  import type { FormContextValue } from '../types.js';

  interface Props {
    /** A pre-configured diblob container */
    container: Container;
    children: Snippet;
  }

  let { container, children }: Props = $props();

  const registries = resolveRegistries(container);
  const contextValue: FormContextValue = {
    ...registries,
    containerRef: container,
  } as FormContextValue;

  setFormContainerContext(contextValue);
</script>

{@render children()}

// packages/react-native/src/components/FormProvider.tsx
import React, { createContext, useMemo } from 'react';
import type { Container } from '@speajus/diblob';
import type { FormContextValue } from '../types.js';
import { resolveRegistries } from '../registry/container.js';

/**
 * React context holding the diblob container and resolved registries.
 */
export const FormContainerContext = createContext<FormContextValue | null>(null);

export interface FormProviderProps {
  /** A pre-configured diblob container */
  container: Container;
  children: React.ReactNode;
}

/**
 * Provides a diblob container to the form tree via React context.
 */
export function FormProvider({ container, children }: FormProviderProps) {
  const contextValue = useMemo<FormContextValue>(() => {
    const registries = resolveRegistries(container);
    return {
      ...registries,
      containerRef: container,
    };
  }, [container]);

  return (
    <FormContainerContext.Provider value={contextValue}>{children}</FormContainerContext.Provider>
  );
}
