// packages/svelte/src/fields/CheckboxesField.svelte
<script lang="ts">
  import type { FieldComponentProps } from '../types.js';
  import { cn } from '../ui/utils.js';

  let { name, value, onChange, onBlur, options, disabled }: FieldComponentProps = $props();

  const selected = $derived(Array.isArray(value) ? value : []);

  function handleChange(optionValue: string, checked: boolean) {
    if (checked) {
      onChange([...selected, optionValue]);
    } else {
      onChange(selected.filter((v: unknown) => v !== optionValue));
    }
  }
</script>

<div class="space-y-2" role="group" aria-label={name}>
  {#each options ?? [] as opt}
    <div class="flex items-center space-x-2">
      <input
        type="checkbox"
        id={`${name}-${opt.value}`}
        checked={selected.includes(opt.value)}
        onchange={(e) => handleChange(opt.value, e.currentTarget.checked)}
        onblur={onBlur}
        {disabled}
        class={cn(
          'peer border-primary ring-offset-background focus-visible:ring-ring h-4 w-4 shrink-0 rounded-sm border focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50',
        )}
      />
      <label
        for={`${name}-${opt.value}`}
        class="text-sm leading-none font-medium peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
      >
        {opt.label}
      </label>
    </div>
  {/each}
</div>

// packages/react-native/src/fields/CheckboxesField.tsx
import React from 'react';
import { View, Text, Pressable } from 'react-native';
import type { FieldComponentProps } from '../types.js';
import { cn } from '../ui/utils.js';

export function CheckboxesField({
  name,
  value,
  onChange,
  onBlur,
  options,
  disabled,
}: FieldComponentProps) {
  const selected = Array.isArray(value) ? (value as string[]) : [];

  const handleChange = (optionValue: string, checked: boolean) => {
    if (checked) {
      onChange([...selected, optionValue]);
    } else {
      onChange(selected.filter((v) => v !== optionValue));
    }
  };

  return (
    <View className="gap-2" testID={name}>
      {(options ?? []).map((opt) => {
        const isChecked = selected.includes(opt.value);
        return (
          <Pressable
            key={opt.value}
            disabled={disabled}
            onPress={() => {
              handleChange(opt.value, !isChecked);
              onBlur();
            }}
            className="flex-row items-center gap-2"
          >
            <View
              className={cn(
                'h-5 w-5 items-center justify-center rounded border',
                isChecked ? 'border-blue-600 bg-blue-600' : 'border-gray-300 bg-white',
                disabled && 'opacity-50',
              )}
            >
              {isChecked && <Text className="text-xs font-bold text-white">✓</Text>}
            </View>
            <Text className="text-sm text-gray-900">{opt.label}</Text>
          </Pressable>
        );
      })}
    </View>
  );
}
