// packages/svelte/src/fields/DateField.svelte
<script lang="ts">
  import type { FieldComponentProps } from '../types.js';
  import Input from '../ui/Input.svelte';

  let { name, value, onChange, onBlur, placeholder, disabled }: FieldComponentProps = $props();
</script>

<Input
  id={name}
  {name}
  type="date"
  value={value ? String(value) : ''}
  oninput={(e) => onChange(e.currentTarget.value)}
  onblur={onBlur}
  {placeholder}
  {disabled}
/>

// packages/react-native/src/fields/DateField.tsx
import React from 'react';
import type { FieldComponentProps } from '../types';
import { Input } from '../ui/Input';

/**
 * Date field using a simple TextInput with date format hint.
 * For a full native date picker, integrate @react-native-community/datetimepicker.
 */
export function DateField({
  name,
  value,
  onChange,
  onBlur,
  placeholder,
  disabled,
}: FieldComponentProps) {
  return (
    <Input
      testID={name}
      value={value ? String(value) : ''}
      onChangeText={(text) => onChange(text)}
      onBlur={onBlur}
      placeholder={placeholder ?? 'YYYY-MM-DD'}
      editable={!disabled}
    />
  );
}
