// packages/svelte/src/fields/ListField.svelte
<script lang="ts">
  import type { FieldComponentProps } from '../types.js';
  import Button from '../ui/Button.svelte';
  import { getFormStateContext } from '../context.js';
  import { createFieldArray } from '../field-array.svelte.js';

  let { name, fieldSchema }: FieldComponentProps = $props();

  const formState = getFormStateContext();
  const { fields, push, remove } = createFieldArray(name, formState);
</script>

<div class="space-y-2">
  {#each fields as item, index}
    <div class="flex items-center gap-2">
      <input
        class="border-input bg-background flex h-10 w-full rounded-md border px-3 py-2 text-sm"
        value={String(item ?? '')}
        oninput={(e) => {
          const newFields = [...fields];
          newFields[index] = e.currentTarget.value;
          formState.setValue(name, newFields);
        }}
      />
      <Button type="button" variant="destructive" size="sm" onclick={() => remove(index)}>
        {#snippet children()}
          Remove
        {/snippet}
      </Button>
    </div>
  {/each}
  <Button type="button" variant="outline" size="sm" onclick={() => push('')}>
    {#snippet children()}
      Add Item
    {/snippet}
  </Button>
</div>

// packages/react-native/src/fields/ListField.tsx
import React from 'react';
import { View } from 'react-native';
import type { FieldComponentProps } from '../types';
import { Input } from '../ui/Input';
import { Button } from '../ui/Button';
import { useFieldArray } from '../hooks/useFieldArray';
import { useFormState } from '../components/FormStateContext';

/**
 * List/array field. Allows adding and removing items.
 */
export function ListField({ name }: FieldComponentProps) {
  const formState = useFormState();
  const { fields, push, remove } = useFieldArray(name, formState);

  return (
    <View className="gap-2">
      {fields.map((item, index) => (
        <View key={index} className="flex-row items-center gap-2">
          <View className="flex-1">
            <Input
              value={String(item ?? '')}
              onChangeText={(text) => {
                const newFields = [...fields];
                newFields[index] = text;
                formState.setValue(name, newFields);
              }}
            />
          </View>
          <Button variant="destructive" size="sm" onPress={() => remove(index)}>
            Remove
          </Button>
        </View>
      ))}
      <Button variant="outline" size="sm" onPress={() => push('')}>
        Add Item
      </Button>
    </View>
  );
}
