// packages/svelte/src/fields/TextField.svelte
<script lang="ts">
  import type { FieldComponentProps } from '../types.js';
  import Input from '../ui/Input.svelte';

  let { name, value, onChange, onBlur, placeholder, disabled }: FieldComponentProps = $props();
</script>

<Input
  id={name}
  {name}
  value={String(value ?? '')}
  oninput={(e) => onChange(e.currentTarget.value)}
  onblur={onBlur}
  {placeholder}
  {disabled}
/>

// packages/react-native/src/fields/TextField.tsx
import React from 'react';
import type { FieldComponentProps } from '../types';
import { Input } from '../ui/Input';

export function TextField({
  name,
  value,
  onChange,
  onBlur,
  placeholder,
  disabled,
}: FieldComponentProps) {
  return (
    <Input
      testID={name}
      value={String(value ?? '')}
      onChangeText={(text) => onChange(text)}
      onBlur={onBlur}
      placeholder={placeholder}
      editable={!disabled}
    />
  );
}
